### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [AcierP/robloxgamebotter#3]
I did everything right, but when I run main.py it says this

Traceback (most recent call last):
  File "(hiding my user info)\main.py", line 1, in <module>
    from roblox import Roblox, RobloxClientMutex
  File "(hiding my user info)\roblox.py", line 5, in <module>
    from PIL import Image, ImageGrab
ModuleNotFoundError: No module named 'PIL'

**Comment by ghost** [comment]
resolved

**Comment by strstrjrkr** [comment]
How did you resolved this, ty
